- name: install packages
  pacman: name={{item}} state=present update_cache=yes
  with_items:
    - xorg-xprop
    - conky
  become: yes

- name: install AUR packages
  shell: yaourt -Q {{item}} || yaourt --noconfirm -S {{item}}
  with_items:
    - perl-anyevent-i3
    - perl-json-xs
    - python-i3-git
    - i3-gnome
    - unagi

- name: install i3 files
  copy: src=i3 dest={{ ansible_env["HOME"] }}/.config/
