- name: install packages
  pacman: name={{item}} state=present update_cache=yes
  with_items:
    - xorg-xprop
  become: yes

- name: install fonts
  copy: src=fonts dest={{ ansible_env["HOME"] }}/.local/share/

- name: mkfontdir
  shell: fc-cache -s

- name: install i3 files
  copy: src=i3 dest={{ ansible_env["HOME"] }}/.config/

